CREATE TABLE THONGBAO {
    NoiDung NVARCHAR(1000);
}

BEGIN
  SA_SYSDBA.CREATE_POLICY(
    policy_name => 'THONGBAO_POLICY', 
    column_name => 'THONGBAO_LABEL'
  );
END;

--
--SELECT *
--FROM DBA_SA_POLICIES
--
--BEGIN
--  SA_SYSDBA.DROP_POLICY(
--    policy_name => 'THONGBAO_POLICY',
--    drop_column => True
--  );
--END;

EXEC SA_SYSDBA.ENABLE_POLICY ('THONGBAO_POLICY'); 

--SELECT * FROM DBA_SA_LEVELS;
--SELECT * FROM DBA_SA_COMPARTMENTS;
--EXECUTE SA_COMPONENTS.DROP_COMPARTMENT('THONGBAO_POLICY','HTTT'); 
--SELECT * FROM DBA_SA_GROUPS;
--SELECT * FROM DBA_SA_GROUP_HIERARCHY; 

EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY',20,'TK','TRUONG KHOA');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY',40,'TDV','TRUONG DON VI');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY',60,'GV','GIANG VIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY',80,'GVU','GIAO VU');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY',100,'NV','NHAN VIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY',120,'SV','SINH VIEN');
    
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY',10,'HTTT','HE THONG THONG TIN');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY',30,'CNPM','CONG NGHE PHAN MEM'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY',50,'KHMT','KHOA HOC MAY TINH'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY',70,'CNTT','CÔNG NGHE TRI THUC'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY',90,'TGMT','THI GIAC MAY TINH'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY',110,'MMT','MANG MAY TINH'); 

EXECUTE SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY',20,'CS1','CO SO 1'); 
EXECUTE SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY',40,'CS2','CO SO 2');