CREATE TABLE ADPRO.THONGBAO (
    ID INT,
    NoiDung NVARCHAR2(500),
    DiaDiem NVARCHAR2(50)
    PRIMARY KEY (ID)
);
/

BEGIN
  SA_SYSDBA.CREATE_POLICY(
    policy_name => 'THONGBAO_POLICY', 
    column_name => 'THONGBAO_LABEL'
  );
END;

--
--SELECT *
--FROM DBA_SA_POLICIES
--
--BEGIN
--  SA_SYSDBA.DROP_POLICY(
--    policy_name => 'THONGBAO_POLICY',
--    drop_column => True
--  );
--END;

EXEC SA_SYSDBA.ENABLE_POLICY ('THONGBAO_POLICY'); 

--SELECT * FROM DBA_SA_LEVELS;
--SELECT * FROM DBA_SA_COMPARTMENTS;
--EXECUTE SA_COMPONENTS.DROP_COMPARTMENT('THONGBAO_POLICY','HTTT'); 
--SELECT * FROM DBA_SA_GROUPS;


EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY',120,'TK','TRUONG KHOA');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY',100,'TDV','TRUONG DON VI');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY',80,'GV','GIANG VIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY',60,'GVU','GIAO VU');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY',40,'NV','NHAN VIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY',20,'SV','SINH VIEN');

    
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY',10,'HTTT','HE THONG THONG TIN');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY',30,'CNPM','CONG NGHE PHAN MEM'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY',50,'KHMT','KHOA HOC MAY TINH'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY',70,'CNTT','CÔNG NGHE TRI THUC'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY',90,'TGMT','THI GIAC MAY TINH'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY',110,'MMT','MANG MAY TINH'); 

EXECUTE SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY',20,'CS1','CO SO 1'); 
EXECUTE SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY',40,'CS2','CO SO 2');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (1, N'Thông báo quan trọng cho Trưởng Khoa.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (2, N'Thông báo quan trọng cho Trưởng Đơn Vị.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (3, N'Thông báo quan trọng cho Giảng Viên.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (4, N'Thông báo quan trọng cho Giáo Vụ.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (5, N'Thông báo quan trọng cho Nhân Viên.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (6, N'Thông báo quan trọng cho Sinh Viên.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (7, N'Thông báo quan trọng về Hệ Thống Thông Tin.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (8, N'Thông báo quan trọng về Công Nghệ Phần Mềm.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (9, N'Thông báo quan trọng về Khoa Học Máy Tính.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (10, N'Thông báo quan trọng về Công Nghệ Tri Thức.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (11, N'Thông báo quan trọng về Thị Giác Máy Tính.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (12, N'Thông báo quan trọng về Mạng Máy Tính.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (13, N'Thông báo quan trọng cho Cơ Sở 1.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (14, N'Thông báo quan trọng cho Cơ Sở 2.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (15, N'Thông báo quan trọng cho Sinh Viên về lĩnh vực Hệ Thống Thông Tin ở Cơ Sở 1');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (16, N'Thông báo quan trọng cho Trưởng Bộ Môn về lĩnh vực Khoa Học Máy Tính ở Cơ Sở 1');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (17, ');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (18, N'Thông báo quan trọng cho Giáo Vụ về vấn đề C.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (19, N'Thông báo quan trọng cho Nhân Viên về vấn đề D.');

INSERT INTO ADPRO.THONGBAO (ID, NoiDung)
VALUES (20, N'Thông báo quan trọng cho Sinh Viên ngành Hệ Thống Thông Tin tại Cơ Sở 1.', CHAR_TO_LABEL('THONGBAO_POLICY', 'SV:HTTT:CS1'));

BEGIN 
SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('THONGBAO_POLICY','ADPRO','THONGBAO');

SA_POLICY_ADMIN.APPLY_TABLE_POLICY ( 
 policy_name => 'THONGBAO_POLICY', 
 schema_name => 'ADPRO', 
 table_name => 'THONGBAO',
 table_options => 'READ_CONTROL',
predicate => NULL 
); 
END; 


GRANT CONNECT TO NV1110;
GRANT SELECT ON ADPRO.THONGBAO TO NV1110; 

EXEC SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY','NV1110','GV:HTTT:CS1');

UPDATE ADPRO.THONGBAO 
SET NoiDung = NoiDung;
COMMIT;

SELECT * FROM DBA_SA_LABELS

BEGIN
--e)
--f)
 SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY','NV1110','TDV:KHMT:CS1'); 
--g)
 SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY','NV1110','TDV:KHMT:CS1,CS2'); 
END;
